<?php

namespace Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EOfferta extends \EOfferta implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'acquirente' => [parent::class, 'acquirente', null],
        "\0".parent::class."\0".'data' => [parent::class, 'data', null],
        "\0".parent::class."\0".'id_offerta' => [parent::class, 'id_offerta', null],
        "\0".parent::class."\0".'importo' => [parent::class, 'importo', null],
        "\0".parent::class."\0".'p_usato_id' => [parent::class, 'p_usato_id', null],
        'acquirente' => [parent::class, 'acquirente', null],
        'data' => [parent::class, 'data', null],
        'id_offerta' => [parent::class, 'id_offerta', null],
        'importo' => [parent::class, 'importo', null],
        'p_usato_id' => [parent::class, 'p_usato_id', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
