<?php

namespace Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EReso extends \EReso implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'acquirente' => [parent::class, 'acquirente', null],
        "\0".parent::class."\0".'data_reso' => [parent::class, 'data_reso', null],
        "\0".parent::class."\0".'descrizione' => [parent::class, 'descrizione', null],
        "\0".parent::class."\0".'id_reso' => [parent::class, 'id_reso', null],
        "\0".parent::class."\0".'prodotto' => [parent::class, 'prodotto', null],
        "\0".parent::class."\0".'stato_reso' => [parent::class, 'stato_reso', null],
        'acquirente' => [parent::class, 'acquirente', null],
        'data_reso' => [parent::class, 'data_reso', null],
        'descrizione' => [parent::class, 'descrizione', null],
        'id_reso' => [parent::class, 'id_reso', null],
        'prodotto' => [parent::class, 'prodotto', null],
        'stato_reso' => [parent::class, 'stato_reso', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
