<?php

namespace Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EIndirizzo extends \EIndirizzo implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'acquirente' => [parent::class, 'acquirente', null],
        "\0".parent::class."\0".'cap' => [parent::class, 'cap', null],
        "\0".parent::class."\0".'comune' => [parent::class, 'comune', null],
        "\0".parent::class."\0".'nome' => [parent::class, 'nome', null],
        "\0".parent::class."\0".'ordine' => [parent::class, 'ordine', null],
        'acquirente' => [parent::class, 'acquirente', null],
        'cap' => [parent::class, 'cap', null],
        'comune' => [parent::class, 'comune', null],
        'nome' => [parent::class, 'nome', null],
        'ordine' => [parent::class, 'ordine', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
