<?php

namespace Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ERimborso extends \ERimborso implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cliente_rimborsato' => [parent::class, 'cliente_rimborsato', null],
        "\0".parent::class."\0".'data_erogazione' => [parent::class, 'data_erogazione', null],
        "\0".parent::class."\0".'id_rimborso' => [parent::class, 'id_rimborso', null],
        "\0".parent::class."\0".'importo' => [parent::class, 'importo', null],
        "\0".parent::class."\0".'prodotto' => [parent::class, 'prodotto', null],
        "\0".parent::class."\0".'venditore' => [parent::class, 'venditore', null],
        'cliente_rimborsato' => [parent::class, 'cliente_rimborsato', null],
        'data_erogazione' => [parent::class, 'data_erogazione', null],
        'id_rimborso' => [parent::class, 'id_rimborso', null],
        'importo' => [parent::class, 'importo', null],
        'prodotto' => [parent::class, 'prodotto', null],
        'venditore' => [parent::class, 'venditore', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
