<?php

namespace Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ERecensione extends \ERecensione implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'acquirente' => [parent::class, 'acquirente', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'prodotto' => [parent::class, 'prodotto', null],
        "\0".parent::class."\0".'segnalazione' => [parent::class, 'segnalazione', null],
        "\0".parent::class."\0".'testo' => [parent::class, 'testo', null],
        "\0".parent::class."\0".'valutazione' => [parent::class, 'valutazione', null],
        'acquirente' => [parent::class, 'acquirente', null],
        'id' => [parent::class, 'id', null],
        'prodotto' => [parent::class, 'prodotto', null],
        'segnalazione' => [parent::class, 'segnalazione', null],
        'testo' => [parent::class, 'testo', null],
        'valutazione' => [parent::class, 'valutazione', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
