<?php

namespace Proxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ESegnalazione extends \ESegnalazione implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'gestita' => [parent::class, 'gestita', null],
        "\0".parent::class."\0".'id_segnalazione' => [parent::class, 'id_segnalazione', null],
        "\0".parent::class."\0".'motivo' => [parent::class, 'motivo', null],
        "\0".parent::class."\0".'recensione' => [parent::class, 'recensione', null],
        "\0".parent::class."\0".'venditore' => [parent::class, 'venditore', null],
        'gestita' => [parent::class, 'gestita', null],
        'id_segnalazione' => [parent::class, 'id_segnalazione', null],
        'motivo' => [parent::class, 'motivo', null],
        'recensione' => [parent::class, 'recensione', null],
        'venditore' => [parent::class, 'venditore', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
